# Configuration Constants for Arbitrum Agent
MIN_ETH_FOR_OPERATIONS = 0.01  # Minimum ETH needed for operations
MIN_ETH_FOR_GAS_BUFFER = 0.005  # Minimum ETH buffer for gas fees
DEFAULT_GAS_LIMIT = 300000
DEFAULT_GAS_PRICE_GWEI = 0.1
HEALTH_FACTOR_THRESHOLD = 1.5
TARGET_HEALTH_FACTOR = 2.5
MAX_SLIPPAGE_PERCENT = 2.0
OPERATION_COOLDOWN_SECONDS = 60