"""
Configuration Constants for Arbitrum DeFi Agent
Centralized configuration management
"""

# Minimum ETH requirements for operations
MIN_ETH_FOR_OPERATIONS = 0.001  # 0.001 ETH minimum for gas operations
MIN_ETH_FOR_GAS_BUFFER = 0.0005  # 0.0005 ETH buffer for gas fees

# Health factor thresholds
MIN_HEALTH_FACTOR = 1.35
TARGET_HEALTH_FACTOR = 1.40
SAFE_HEALTH_FACTOR = 1.40
HEALTH_FACTOR_THRESHOLD = 1.35

# Operational limits
MAX_CONSECUTIVE_FAILURES = 3
OPERATION_COOLDOWN = 130
OPERATION_COOLDOWN_SECONDS = 130

# Gas optimization settings
DEFAULT_GAS_LIMIT = 200000
DEFAULT_GAS_PRICE = 100000000  # 0.1 gwei in wei
DEFAULT_GAS_PRICE_GWEI = 0.1
DEFAULT_GAS_MULTIPLIER = 1.2
EMERGENCY_GAS_MULTIPLIER = 2.0

# Borrowing parameters
MIN_BORROW_AMOUNT = 0.5
MIN_BORROW_AMOUNT_USD = 0.5
MAX_BORROW_AMOUNT = 100.0
MAX_BORROW_AMOUNT_USD = 100.0
MAX_BORROW_PERCENTAGE = 0.8
GROWTH_TRIGGER_THRESHOLD = 12.0
GROWTH_TRIGGER_THRESHOLD_USD = 12.0
COOLDOWN_PERIOD = 130

# Fixed-value distribution amounts
GROWTH_BORROW_AMOUNT = 10.20
CAPACITY_BORROW_AMOUNT = 5.50
GROWTH_MIN_CAPACITY = 12.0
CAPACITY_MIN_CAPACITY = 7.0

# Slippage
MAX_SLIPPAGE_PERCENT = 2.0

# Network configuration
ARBITRUM_MAINNET_CHAIN_ID = 42161
ARBITRUM_SEPOLIA_CHAIN_ID = 421614

# Token allocation for swaps (percentages) - Growth path
GROWTH_DAI_SUPPLY = 3.00
GROWTH_WBTC_SWAP_SUPPLY = 3.00
GROWTH_WETH_SWAP_SUPPLY = 2.00
GROWTH_ETH_GAS_RESERVE = 1.10
GROWTH_DAI_TRANSFER = 1.10

# Token allocation for swaps - Capacity path
CAPACITY_DAI_SUPPLY = 1.10
CAPACITY_WBTC_SWAP_SUPPLY = 1.10
CAPACITY_WETH_SWAP_SUPPLY = 1.10
CAPACITY_ETH_GAS_RESERVE = 1.10
CAPACITY_DAI_TRANSFER = 1.10

# Validation thresholds
MIN_COLLATERAL_USD = 10.0
MAX_DEBT_RATIO = 0.75

# RPC settings
RPC_TIMEOUT_SECONDS = 30
MAX_RPC_RETRIES = 3
MAX_RETRIES = 3
RETRY_DELAY = 2

# API configuration
REQUEST_TIMEOUT = 10
PRICE_CACHE_DURATION = 300

print("✅ Configuration constants loaded successfully")
